import type { LucideIcon } from "lucide-react";
import {
    ShoppingCart,
    Code2,
    Landmark,
    HeartPulse,
    Truck,
    Factory,
    GraduationCap,
    Building2,
    Plane,
    Film,
    Shield,
    Zap,
    Wifi,
    Briefcase,
    BookOpen,
    Car,
    HardHat,
    UtensilsCrossed,
} from "lucide-react";

export interface Industry {
    title: string;
    subtitle: string;
    description: string;
    icon: LucideIcon;
    gradient: string;
    accentColor: string;
    borderGlow: string;
}

export const industries: Industry[] = [
    {
        title: "E-Commerce & Retail",
        subtitle: "Dominating the Digital Storefront",
        description: "Stop settling for systems that buckle under pressure. We build high-performance marketplaces and omnichannel ecosystems designed for longevity. The result? Flawless checkouts and inventory that never loses count.",
        icon: ShoppingCart,
        gradient: "from-orange-500/30 via-amber-500/20 to-transparent",
        accentColor: "text-orange-400",
        borderGlow: "group-hover:shadow-orange-500/20",
    },
    {
        title: "SaaS & Technology Product Companies",
        subtitle: "Architecture That Clears the Way",
        description: "Eliminate technical debt and accelerate your evolution. We build solid foundations that turn your tech stack into a weapon, moving you from MVP to market leader at record speed.",
        icon: Code2,
        gradient: "from-blue-500/30 via-cyan-500/20 to-transparent",
        accentColor: "text-blue-400",
        borderGlow: "group-hover:shadow-blue-500/20",
    },
    {
        title: "Fintech & Financial Services",
        subtitle: "Secure Finance. Absolute Precision",
        description: "In finance, \"compliance\" is the floor, not the ceiling. We build secure, high-performance payment platforms with total transparency. You'll never wonder \"Where is it?\" with our predictable delivery.",
        icon: Landmark,
        gradient: "from-emerald-500/30 via-green-500/20 to-transparent",
        accentColor: "text-emerald-400",
        borderGlow: "group-hover:shadow-emerald-500/20",
    },
    {
        title: "Healthcare & HealthTech",
        subtitle: "Frictionless Flow for Patient Care",
        description: "We build interoperable portals and health platforms that prioritize data integrity. Reliability isn't optional here—we handle the technical complexity so you can focus on the human impact.",
        icon: HeartPulse,
        gradient: "from-rose-500/30 via-pink-500/20 to-transparent",
        accentColor: "text-rose-400",
        borderGlow: "group-hover:shadow-rose-500/20",
    },
    {
        title: "Logistics, Supply Chain & Transportation",
        subtitle: "Operations That Never Miss a Beat",
        description: "High-movement environments demand high-reliability tech. We build logistics platforms and operational dashboards that turn data into direction. Predictable execution (No Black Boxes) for a world that never stops.",
        icon: Truck,
        gradient: "from-amber-500/30 via-yellow-500/20 to-transparent",
        accentColor: "text-amber-400",
        borderGlow: "group-hover:shadow-amber-500/20",
    },
    {
        title: "Manufacturing & Industrial",
        subtitle: "Digitizing the Industrial Floor",
        description: "Workflow automation built for the plant floor, not the boardroom. We build for longevity, ensuring your production systems are as robust as the machines they manage.",
        icon: Factory,
        gradient: "from-slate-500/30 via-zinc-500/20 to-transparent",
        accentColor: "text-slate-400",
        borderGlow: "group-hover:shadow-slate-500/20",
    },
    {
        title: "EdTech & Learning Platforms",
        subtitle: "Learning Systems That Scale with You",
        description: "Don't let an enrollment spike crash your classroom. We build virtual learning environments designed for massive usage. We trade technical noise for predictable performance, keeping your students connected.",
        icon: GraduationCap,
        gradient: "from-violet-500/30 via-purple-500/20 to-transparent",
        accentColor: "text-violet-400",
        borderGlow: "group-hover:shadow-violet-500/20",
    },
    {
        title: "Real Estate",
        subtitle: "Transaction Tech Built for Speed",
        description: "Property listing platforms and transaction workflows that remove the friction from discovery. We focus on the outcome—faster engagement and smoother operations—backed by an unbreakable foundation.",
        icon: Building2,
        gradient: "from-teal-500/30 via-cyan-500/20 to-transparent",
        accentColor: "text-teal-400",
        borderGlow: "group-hover:shadow-teal-500/20",
    },
    {
        title: "Hospitality, Travel & Tourism",
        subtitle: "Guest Journeys Reimagined",
        description: "Booking platforms and customer portals that stay invisible so your service can stand out. We build for the guest journey, ensuring your tech stack handles peak season with zero stress.",
        icon: Plane,
        gradient: "from-sky-500/30 via-blue-500/20 to-transparent",
        accentColor: "text-sky-400",
        borderGlow: "group-hover:shadow-sky-500/20",
    },
    {
        title: "Media, Entertainment & Digital Experiences",
        subtitle: "Content Hubs That Command Attention",
        description: "Why be flat when you can be immersive? We build interactive 3D sites and storytelling platforms with clear communication. Catchy experiences, high-performance results.",
        icon: Film,
        gradient: "from-fuchsia-500/30 via-pink-500/20 to-transparent",
        accentColor: "text-fuchsia-400",
        borderGlow: "group-hover:shadow-fuchsia-500/20",
    },
    {
        title: "Insurance & InsurTech",
        subtitle: "Underwriting Accuracy at Scale",
        description: "Precision engineering for an industry that demands it. We support insurers with claims platforms and risk analytics built for performance and compliance. Solid foundations for complex risk.",
        icon: Shield,
        gradient: "from-indigo-500/30 via-blue-500/20 to-transparent",
        accentColor: "text-indigo-400",
        borderGlow: "group-hover:shadow-indigo-500/20",
    },
    {
        title: "Energy, Utilities & Environment",
        subtitle: "Visibility Across Distributed Assets",
        description: "Improving safety and performance requires data you can trust. We build monitoring dashboards and asset management platforms that solve the visibility problem, keeping critical infrastructure stable and safe.",
        icon: Zap,
        gradient: "from-yellow-500/30 via-lime-500/20 to-transparent",
        accentColor: "text-yellow-400",
        borderGlow: "group-hover:shadow-yellow-500/20",
    },
    {
        title: "Telecom & Connectivity Services",
        subtitle: "Self-Service with Style and Speed",
        description: "Stop frustrating your customers with legacy friction. We design portals and billing systems with predictable milestones. Improved service delivery, total operational control.",
        icon: Wifi,
        gradient: "from-cyan-500/30 via-teal-500/20 to-transparent",
        accentColor: "text-cyan-400",
        borderGlow: "group-hover:shadow-cyan-500/20",
    },
    {
        title: "Professional Services & Consulting Firms",
        subtitle: "Execution Efficiency for Elite Teams",
        description: "Delivery management platforms that fuel your team's utilization. Success isn't just \"shipping the code\"—it's providing the tools that help your team collaboration and growth.",
        icon: Briefcase,
        gradient: "from-neutral-500/30 via-stone-500/20 to-transparent",
        accentColor: "text-neutral-400",
        borderGlow: "group-hover:shadow-neutral-500/20",
    },
    {
        title: "Education",
        subtitle: "Campus Infrastructure (Built for the Long Term)",
        description: "Replace fragmented academic systems with a cohesive digital foundation. We build administration portals and collaboration platforms that scale with your mission, not just your enrollment.",
        icon: BookOpen,
        gradient: "from-purple-500/30 via-violet-500/20 to-transparent",
        accentColor: "text-purple-400",
        borderGlow: "group-hover:shadow-purple-500/20",
    },
    {
        title: "Automotive & Mobility",
        subtitle: "Mobility Apps That Keep You Moving",
        description: "From vehicle configurators to dealership systems, we build apps that feel great and perform even better. Better customer journeys, smoother operations—digital presence with zero drag.",
        icon: Car,
        gradient: "from-red-500/30 via-rose-500/20 to-transparent",
        accentColor: "text-red-400",
        borderGlow: "group-hover:shadow-red-500/20",
    },
    {
        title: "Construction, Infrastructure & Engineering",
        subtitle: "Project Certainty Through Predictable Sprints",
        description: "Infrastructure-heavy businesses can't afford the \"Where is it?\" trap. We build field-tracking systems and vendor dashboards using transparent execution. Engineering certainty for a world of concrete.",
        icon: HardHat,
        gradient: "from-orange-600/30 via-amber-600/20 to-transparent",
        accentColor: "text-orange-500",
        borderGlow: "group-hover:shadow-orange-600/20",
    },
    {
        title: "Food, Delivery & On-Demand Services",
        subtitle: "Real-Time Powerhouses for Infinite Demand",
        description: "On-demand startups live or die by execution. We build the ordering platforms and partner portals needed for massive scale, ensuring your service never misses a beat.",
        icon: UtensilsCrossed,
        gradient: "from-lime-500/30 via-green-500/20 to-transparent",
        accentColor: "text-lime-400",
        borderGlow: "group-hover:shadow-lime-500/20",
    },
];
